import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/providers/query-provider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { ContextClient } from "@/lib/context-client";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lacak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <QueryProvider>
          <ContextClient>{children}</ContextClient>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
